### ISSUE TITLE
大佬，这是不是少传了一个Title?

### ISSUE THREAD

**Issue by RunnerHong** [wuhan005/Asteroid_backend#1]
https://github.com/wuhan005/Asteroid_backend/blob/b43b3f7a62c2434b19aa277170f37cd0f1ee2e7c/client.go#L44-L47

**Comment by wuhan005** [comment]
嗯 是的，这份后端代码在大屏 Unity 那边更新后未进行更新，可能有一些数据的格式对不上。


我之后更新下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: RunnerHong <notifications@github.com&gt;
发送时间: 2020年12月7日 17:05
收件人: wuhan005/Asteroid_backend <Asteroid_backend@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[wuhan005/Asteroid_backend] 大佬，这是不是少传了一个Title? (#1)

**Comment by wuhan005** [comment]
已更新

https://github.com/wuhan005/Asteroid_backend/blob/master/client.go#L45
